name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
  pull_request: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4
          
      # Docker image Build
      - name: Build Docker Image
        run: 
          docker build -t actions-app:${{ github.sha }} .
          docker tag actions-app:${{ github.sha }} ${{ secrets.ECR_REPOSITORY_URI }}/actions-cicd:latest

      # Set up AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
 
      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }} 

      # Push image to Amazon ECR
      - name: Push image to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/actions-cicd:latest
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


