name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
  pull_request: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4
          
      # Docker image Build
      - name: Build Docker Image
        run: docker build -t hello-eyego .

